services:
  web:
    build: "."
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: db
      RABBITMQ_HOST: rabbit
    depends_on:
      - rabbit
      - db
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # ports:
    volumes:
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    env_file:
      - .env
  rabbit:
    image: rabbitmq:3.8
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  consumer:
    build:
      context: ./thumbnailGenerator
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbit
      - db
    environment:
      MYSQL_HOST: db
      RABBITMQ_HOST: rabbit
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    command: ["bash", "/waitForRabbit.sh"]
    volumes:
      - ./thumbnailGenerator/waitForRabbit.sh:/waitForRabbit.sh
      - ./thumbnailGenerator/thumbnailGenerator.js:/thumbnailGenerator.js
      - ./thumbnailGenerator/package.json:/package.json
volumes:
  db_data:
